### PR TITLE
Initial GitHubStory

### PR DESCRIPTION
**Pull request by wallina2018**

### CODE REVIEW

**Comment by wallina2018** [comment]
Checking if I can close the pull request and merge this branch into the master

**Comment by Astudent1** [comment]
One more step closer!

**Comment by Astudent1** [comment]
Cheers!

**Comment by Astudent1** [comment]
confirm, now merge

**Comment by Astudent1** [comment]
Moving on!

**Comment by Astudent1** [comment]
I am trying to merge all the pull requests now

**Comment by Astudent1** [comment]
All right!

**Pull request merged**
